### ISSUE TITLE
Invalid AsyncAPI document when generating playground sample

### ISSUE THREAD

**Issue by BAPostma** [asyncapi/generator#109]
When taking the example AsyncAPI document from the playground (https://playground.asyncapi.io) and saving it in a file [example.yaml](https://github.com/asyncapi/generator/files/3559748/example.yaml.txt).

Running `~$ ag example.yaml markdown` using `asyncapi-generator@0.13.1`, gives the following, non-descriptive error:

```
Something went wrong:
Error: Invalid AsyncAPI document
    at parse (/usr/local/lib/node_modules/asyncapi-generator/node_modules/asyncapi-parser/lib/parser.js:93:11)
    at async Generator.generateFromString (/usr/local/lib/node_modules/asyncapi-generator/lib/generator.js:169:22)
    at async Generator.generateFromFile (/usr/local/lib/node_modules/asyncapi-generator/lib/generator.js:201:7)
```

**Comment by fmvilas** [comment]
Yeah, sorry, the playground is running on AsyncAPI 2.0.0-rc1 and an outdated version of the generator. The new generator doesn't support 2.0.0-rc1 but 2.0.0-rc2. It doesn't support both because they are release candidates so it's always supporting the last.

I'm currently working on updating the playground. In the meantime, you may find useful using the converter package to convert from 2.0.0-rc1 to 2.0.0: https://github.com/asyncapi/converter.

**Comment by BAPostma** [comment]
Thanks @fmvilas, I've just tried the converter, but with no success.
Attempted to change the version number to `2.0.0-rc2` as well, but this is not supported.

```
Something went wrong:
Error: AsyncAPI version is missing or unsupported: 2.0.0.
```

**Comment by fmvilas** [comment]
Where are you trying? If possible, can you share your asyncapi file?

**Comment by BAPostma** [comment]
Sorry, only was able to look at this intermittently. With the release of `v0.25.0` the document version 2.0.0 is now supported.
