### ISSUE TITLE
Couldn't find server with name mosquitto or emqx?

### ISSUE THREAD

**Issue by fangchih** [asyncapi/generator#186]
I tried the "getting start" but seems get no luck, anything I missed?

```
❯ ag mqtt.yml nodejs -p server=mosquitto
Something went wrong:
Error: Couldn't find server with name mosquitto.
    at Generator.validateTemplateConfig (/Users/anchungmin/.nvm/versions/node/v12.13.0/lib/node_modules/asyncapi-generator/lib/generator.js:593:28)
    at Generator.generate (/Users/anchungmin/.nvm/versions/node/v12.13.0/lib/node_modules/asyncapi-generator/lib/generator.js:128:18)
    at async /Users/anchungmin/.nvm/versions/node/v12.13.0/lib/node_modules/asyncapi-generator/cli.js:128:7
```

**Comment by fmvilas** [comment]
Hi @fangchih! Can you share the content of the `mqtt.yml` file? At least the `servers` section. Thanks!

**Comment by derberg** [comment]
@fangchih with `-p` flag you specify template specific parameters that can be passed to the template. In case of `nodejs` and `nodejs-ws` templates, the `server` parameters is mandatory. It is because AsyncAPI allows you to specify multiple different servers, and for generated code you need to specify explicitly what `server` info should be used. In your `mqtt.yml` file you should have something similar to this example https://github.com/asyncapi/generator/blob/master/test/docs/streetlights.yml#L18 where you would pass the following info to the generator `-p server=production`.

I hope it helps. I'm gonna close this issue but if you need more help then feel free to reopen.
