### ISSUE TITLE
[HTML template] Support <base href="{{param.href}}"></base> in index.html

### ISSUE THREAD

**Issue by stefanseeger** [asyncapi/generator#205]
When the generator is running inside an express app with multiple routings, the links to the css and js files are always linked to the domain root e.g.

* http://root/css/main.css
* http://root/js/main.js

With a dynamic <base href=""> it could be executed in any folder.

**Comment by fmvilas** [comment]
Hi @stefanseeger. Thanks for opening the issue. I updated the title to include "[HTML template]" because I'm assuming this is the template you're referring to, right? If that's the case, we could implement it using template parameters as we did [here](https://github.com/asyncapi/generator/blob/master/templates/html/.partials/sidebar.html#L31).

As always any contribution is welcome. We'd be happy to guide you.

**Comment by stefanseeger** [comment]
Problem solved.
Thank you for your help!

best regards,
Stefan
