### ISSUE TITLE
nullable does not work ?

### ISSUE THREAD

**Issue by ymarillet** [asyncapi/generator#33]
As defined in the specification, any Schema Object MAY have a "nullable" property, but I can't make it working in the editor, nor find it in the spec implementation (https://github.com/asyncapi/asyncapi/blob/master/schema/asyncapi.json)

Should it be removed from the doc ?

**Comment by fenollp** [comment]
Could these help?
* https://github.com/wework/json-schema-to-openapi-schema
* https://github.com/mikunn/openapi-schema-to-json-schema

I'd love a solution to this issue too!

Also, since AsyncAPI isn't OpenAPI why not just use a subset of JSON Schema Draft XY? OpenAPI schemas are not exactly a subset + history has shown people get confused between the two + there are way more JSON Schema validators/tools than there are for OpenAPI Schemas...

I can't wait for both these standards to support "here's my schema in language XYZ" :)

**Comment by fmvilas** [comment]
@fenollp I'm glad you ask for multiple schema support. It's already implemented in the spec for version 2.0.0, which should be ready by May this year. Check it out:

* https://github.com/asyncapi/asyncapi/issues/113
* https://github.com/asyncapi/asyncapi/pull/158

**Comment by fenollp** [comment]
@fmvilas Nice! May isn’t far off too :)
We’re going to need to be able to specify schemas in more than one formats though at some point. It appears you’d prefer to allow as of yet unspec-ed Overlays instead of allowing multiple schema formats for the same payload. Why not. I guess there are issues I’m not seeing with the latter. 
Anyway we may rely on something that translates for example our protobuf to JSON schema but these two have semantics that the other misses so I’m not sure about that yet.

**Comment by fmvilas** [comment]
We removed support for multiple formats on a single message for simplicity of the spec because that's not the case of many people. Overlays will allow you to do that. In any case, if the message is not exactly the same, they should be different messages.

**Comment by fmvilas** [comment]
This was fixed by #204. Closing.
