### ISSUE TITLE
one entry in nonRenderableFiles: []

### ISSUE THREAD

**Issue by felixplatteau** [asyncapi/generator#403]
would be nice if string is supported in case of one entry + better error if the link to file is wrong

**Comment by derberg** [comment]
Please provide an error message that you're getting when the link to file is wrong.

Docs explain well how that works, but we should make sure the error is also helpful

**Comment by derberg** [comment]
Details not provided

**Comment by jonaslagoni** [comment]
@derberg I can provide some insight here. When you provide `nonRenderableFiles` options it is guess work (unless you done it a few time) whether it actually stop the file from being rendered.

> better error if the link to file is wrong

And by this I think it means adding an error if no files where found, this would be useful for me a couple of time.



> would be nice if string is supported in case of one entry

What is meant here is just instead of `nonRenderableFiles: ["path"]` to do `nonRenderableFiles: "path"`. For me this is irrelevant though.

**Comment by derberg** [comment]
@jonaslagoni oh, so these are two different features, but yeah, thanks for clarification 😄

**Comment by derberg** [comment]
I'm closing it for now. There was no further interest in this, we can always reopen when needed
