### ISSUE TITLE
docker run fetches npm dependencies each time

### ISSUE THREAD

**Issue by mbande** [asyncapi/generator#449]
#### Describe the bug
whenever a want to generate html template based on provided docker command, it goes to fetch all node dependencies again.

#### How to Reproduce
as provided in [docs](https://github.com/asyncapi/generator#cli-usage-with-docker)

#### Expected behavior
the docker file should be organized in a way that it can use the installed npm modules in container volume

**Comment by jonaslagoni** [comment]
Thanks for the issue @mbande. This is actually expected behaviour because each template defines which dependencies are required and are installed when you run the container, however as soon as the container shutsdown it forgets about it. If you want to preserve the dependencies you could make a volume bind to (I am assuming it is where it places the dependencies) `/usr/local/lib/node_modules` inside the container.

**Comment by derberg** [comment]
@mbande hey, do you have more questions? does it work for you better after mounting volume with deps?

**Comment by Z5eyhS0uubejR0SVmX2O** [comment]
I would argue a container image should not need to pull a slew of software dependencies from the network in order to function.

Our use case only includes `@asyncapi/html-template` so we have created a custom image that has a `Dockerfile` line of:
```RUN ag /app/sample_contract.yaml @asyncapi/html-template```

I would happily paste the rest of the `Dockerfile` but I don't own the IP rights and am not authorized to share it (closed source project).

I am guessing others would prefer this approach also. I don't know the full breadth, but some kind of general pre-cache for the Docker image seems appropriate to me.

**Comment by derberg** [comment]
Release 1.2 enables support for latest node and npm and fixes all known installation issues. In case you see some other issues, please create a new issue. Please use `--debug` flag when you experience issues with the generator and in the issues mention the troubleshooting logs. Thanks!
