### ISSUE TITLE
Can't reference local file in definitions

### ISSUE THREAD

**Issue by ovidals** [asyncapi/generator#50]
Hi, I'm trying to reference a json definition from one file to another in the same directory but when I execute the asyncapi-generator I get an error.

Folder Structure:
![image](https://user-images.githubusercontent.com/6129112/55072398-492ef080-508b-11e9-86b0-cf311dcdaa75.png)

Inside push.json
` "definitions": {
    "push-data": {
      "$ref": "file:../../../schema/v1/push/push-data.json"
    }
  }`

I execute "node generate_html.js" inside the generator folder and I get this:

> Can not dereference the JSON obtained from the content of the AsyncAPI specification file
{
  "errno": -2,
  "code": "ENOENT",
  "syscall": "open",
  "path": "/../../../schema/v1/push/push-data.json",
  "name": "Error",
  "message": "Error opening file \"/../../../schema/v1/push/push-data.json\" 
ENOENT: no such file or directory, open '/../../../schema/v1/push/push-data.json'",
  "stack": "Error: Error opening file \"/../../../schema/v1/push/push-data.json\" 
ENOENT: no such file or directory, open '/../../../schema/v1/push/push-data.json'
    at ReadFileContext.callback (/var/www/html/node_modules/json-schema-ref-parser/lib/resolvers/file.js:52:20)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:242:13)
Error: ENOENT: no such file or directory, open '/../../../schema/v1/push/push-data.json'"
}
{
  "errno": -2,
  "code": "ENOENT",
  "syscall": "open",
  "path": "/../../../schema/v1/push/push-data.json",
  "name": "Error",
  "message": "Error opening file \"/../../../schema/v1/push/push-data.json\" 
ENOENT: no such file or directory, open '/../../../schema/v1/push/push-data.json'",
  "stack": "Error: Error opening file \"/../../../schema/v1/push/push-data.json\" 
ENOENT: no such file or directory, open '/../../../schema/v1/push/push-data.json'
    at ReadFileContext.callback (/var/www/html/node_modules/json-schema-ref-parser/lib/resolvers/file.js:52:20)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:242:13)
Error: ENOENT: no such file or directory, open '/../../../schema/v1/push/push-data.json'"
}
(node:14770) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

I tryed both "file:../" and "file://../".

Thank you.

**Comment by fmvilas** [comment]
Thanks for reporting @ovidals.

It seems related to https://github.com/APIDevTools/json-schema-ref-parser/issues/20. We're using `dereference` without a base path/URL here: https://github.com/asyncapi/generator/blob/master/lib/parser.js#L28.

It would be awesome to fix it and allow the CLI to specify what do you want as your base path/URL.

Example:

```
ag -o generated --baseURL file:///Users/bob/my-asyncapi-project/ asyncapi.yml html
```

**Comment by MikeRalphson** [comment]
Wouldn't the `baseURL` be the resolved path or url of the input document (in almost all cases)?

**Comment by fmvilas** [comment]
Yeah, this might be a good default.

**Comment by derberg** [comment]
I started working on this issue and I can't recall from yesterday's community call. Is it the expectation that this is going to be fixed only for latest version or previous too? I'm asking because:
- obviously in latest master parser.js doesn't exist as parsing is delegated to asyncapi-parser package and all the magic at the end happens in go parser
- this means (if it doesn't work with go parser too - I didn't check that yet) fix have to be done in 2 places
- generator has no release branches, so if we want to have a fix for old version we would have to make a branch out of the 0.6.5 tag (latest release tag, or later) so the fix is provided there and can be separately released

above sounds nasty but because current generator is not backward compatible with older specs, it is a must.
Alternative:
1. Just make sure it works with latest generator, latest spec and readme should simply explain users of old spec to first convert it from 1->2 using https://github.com/asyncapi/converter
2. Plug in the converter https://github.com/asyncapi/converter and assure backward compatibility this way, because it is anyway needed for the community I guess. I can't imagine if option 1 would be an overhead for a user. Me as a user I would prefer to convert once on my own, but this is a use case where I create asyncapi manually, not generate it

What others think?

**Comment by fmvilas** [comment]
I'd go for option 1. We’re not going to support 1.x versions anymore so that seems the best way to me.

Regarding release branches, I’m not bothering yet with them because it’s still version 0.x. My idea was to start the regular release process once we reach 1.0.0 but I’m open to other suggestions.

**Comment by fmvilas** [comment]
The generator is now using the new parser, which takes care of this. Closing.
