### ISSUE TITLE
Recursive model

### ISSUE THREAD

**Issue by mflorczak** [asyncapi/generator#620]
Describe the bug
I want to create tree structure which each object has list of the same types.

How to Reproduce
This is my schemas components
![image](https://user-images.githubusercontent.com/36895020/126633685-86dac13d-47e3-4358-97ce-6a0a32420946.png)

It is recursive tree model
![image](https://user-images.githubusercontent.com/36895020/126633701-442a4136-1c44-456d-850b-c1e61bde2477.png)

And this is error
![image](https://user-images.githubusercontent.com/36895020/126633714-b5c3dd97-a3cf-403c-873b-74f39a49daf6.png)

Expected behavior
As a user I want to be able to create recursive model eg. trees graphs etc.

**Comment by magicmatatjahu** [comment]
@mflorczak Hi! Could you add more information like which template do you want to use, which schema is circular (I guess `NodeAdto` -> `NodeAdto`), etc?

Have in mind that some templates doesn't support specification with the circular references.

**Comment by mflorczak** [comment]
Hello! I used java-spring-template

type: object
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
  created:
    type: string
    format: date-time
  stamp:
    type: string
    format: date-time
  children:
    type: array
    items:
      $ref: "../async-consume.yaml#/components/schemas/NodeAdto"


channels:

  flexible-production:
    description: flexible production topic.
    publish:
      summary: Listens on shopfloor execution context topic.
      operationId: flp
      message:
        name: templatePointerMessage
        title: template with decoded name
        summary: template pointer message.
        contentType: application/json
        payload:
          $ref: '#/components/schemas/TemplatePointerAdto'

components:
  schemas:
    TemplatePointerAdto:
      $ref: './schemas/TemplatePointer.yaml'
    TemplateAdto:
      $ref: './schemas/Template.yaml'
    ProcessAdto:
      $ref: './schemas/Process.yaml'
    NodeAdto:
      $ref: './schemas/Node.yaml'
    NodeLinkAdto:
      $ref: './schemas/NodeLink.yaml'

type: object
description: template pointer.
events:
  - TEMPLATE_POINTER_CREATED
properties:
  itemId:
    type: string
  template:
    $ref: "../async-consume.yaml#/components/schemas/NodeAdto"

**Comment by magicmatatjahu** [comment]
Currently we support the circular refs in the spec, but not in every places (more info [here](https://github.com/asyncapi/parser-js/issues/293)). Generator can parse/validate your spec and pass it to the template. The given error is throw by this line https://github.com/asyncapi/java-spring-template/blob/master/filters/all.js#L101 Native `JSON. stringify` function doesn't support the circular refs, so it's not a problem with generator, but it's related with template itself. I will close the issue, and please continue the discussion [here](https://github.com/asyncapi/java-spring-template/issues/150). 

Also please don't cut the error, because this line:

![image](https://user-images.githubusercontent.com/20404945/126644785-899f7810-33de-495f-b622-0f7bc53ad2ce.png)

is most important :P
