### ISSUE TITLE
Wrong link to semver version syntax

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#691]
#### Describe the bug
In the generator docs https://github.com/asyncapi/generator/blob/master/docs/authoring.md#configuration-file for the configuration `generator` we link to https://docs.npmjs.com/misc/semver which is broken. 

#### Expected behavior
I am not quite sure where the correct link has gone 🤔

**Comment by jonaslagoni** [comment]
Maybe this? https://docs.npmjs.com/cli/v6/using-npm/semver

**Comment by lkmandy** [comment]
Hi @jonaslagoni @alequetzalli @derberg
I'll like to work on this issue; to get started with understanding the generator project and the PR workflow at AsyncAPI

**Comment by alequetzalli** [comment]
@lkmandy, totally feel free to pick this up!

When you open a PR, just make sure you tag @jonaslagoni and @derberg ⭐

**Comment by lkmandy** [comment]
Great, thanks @alequetzalli

**Comment by lkmandy** [comment]
@jonaslagoni I came across this youtube video on [Semantic versioning](https://bit.ly/3vUuf0k) authored by npm that shows your [proposed link]( https://docs.npmjs.com/cli/v6/using-npm/semver) is the right one; the contents match exactly what was previously on this [broken link](https://docs.npmjs.com/misc/semver) 

I also noticed the proposed link [https://docs.npmjs.com/cli/v6/using-npm/semver](https://docs.npmjs.com/cli/v6/using-npm/semver) is dependent on a particular version. This link might soon become broken again since `V6.x` is currently listed as a `legacy release` (as seen on this same link) and the `semver` section is yet to be added to the current release `V8.x`
In addition, since the `version number` is a static part of the link, I believe It will constantly need to be updated to match the latest versions from npm

Here are some alternatives I think provide a decent explanation of semantic versioning (semver) concepts and syntax:

1. npm docs - About semantic versioning [https://docs.npmjs.com/about-semantic-versioning](https://docs.npmjs.com/about-semantic-versioning)
- It's very summarized and lays emphasis on the most important details
- A big plus - It contains a link  to  the youtube video I mentioned above, which gives a practical explanation of the syntax for semver

2. nodejs docs - Semantic Versioning using npm [https://nodejs.dev/learn/semantic-versioning-using-npm](https://nodejs.dev/learn/semantic-versioning-using-npm)
- It provides a simple and detailed explanation of the semver concept and syntax with examples.
- It's very beginner-friendly

**Comment by jonaslagoni** [comment]
@lkmandy great research!

Feel free to open a PR with the change you would like to go with 🙂

**Comment by lkmandy** [comment]
@derberg I noticed this issue is still marked as open after the PR was merged.
I linked the issue in the commit message. Did I miss something?

**Comment by derberg** [comment]
@lkmandy I think it is because your comment in PR said `Fixes issue #691` while, to automatically close the issue after merge, it should say `Fixes #691`, at least I think so.

**Comment by lkmandy** [comment]
Noted, thanks.
