### ISSUE TITLE
Should messageTraits be able to handle payload?

### ISSUE THREAD

**Issue by MagnusKlingenberg** [asyncapi/generator#934]
Is it intentional or a missing feature that messageTraits do not support payload?

Since this would make it a good way to have multiple messages share some common parameters without making all variants one huge message.

**Comment by magicmatatjahu** [comment]
@MagnusKlingenberg Intentional, due to the possible complexity of the payload. If you need complex "logic" for payload then use words like `allOf`, `oneOf` etc to describe a complex use case. You are probably wondering why `headers` can be defined in a trait - due to the fact that it is a map (key -> value) you can concatenate common keys using traits - the payload case is excluded because it would create too much of complex to understand what the resulting payload would look like - it doesn't always have to be an object but e.g. a union of a string and an object.

Btw. for the future, please create such an issue in the `spec` repo, because your issue/question is related to the spec, not to generator :)

**Comment by MagnusKlingenberg** [comment]
@magicmatatjahu Thank you that answers the question.

**Comment by MagnusKlingenberg** [comment]
@magicmatatjahu Thank you that answers the question.
