### ISSUE TITLE
[Docs Bug 🐞 report]: broken hyperlinks

### ISSUE THREAD

**Issue by kakabisht** [asyncapi/generator#935]
### Describe the bug you found in AsyncAPI Docs.

I would like to contribute to Async API docs, by fixing the broken hyperlinks

### Attach any resources that can help us understand the issue.

Following hyperlinks are broken:
1. https://www.asyncapi.com/docs/tools/generator/asyncapi-document - Template Context
2. https://www.asyncapi.com/docs/tools/generator/parser- Template Context
3. https://www.asyncapi.com/docs/tools/generator/template-development - Render Engine

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Florence-Njeri** [comment]
Hi @kakabisht the links are breaking because either the links are outdated or have a .md extension. For example:
1. In the [AsyncAPI Document](https://www.asyncapi.com/docs/tools/generator/asyncapi-document) has these broken links:
[Template Context](https://www.asyncapi.com/docs/tools/generator/asyncapi-context) should be https://www.asyncapi.com/docs/tools/generator/template-context
2. In the [Parser]() the link to the [AsyncAPI Document](https://www.asyncapi.com/docs/tools/generator/asyncapi-document.md) is breaking. Remove the .md at the end of the link for to to be -> https://www.asyncapi.com/docs/tools/generator/asyncapi-document

**Comment by Florence-Njeri** [comment]
@kakabisht Yes, go ahead

**Comment by kakabisht** [comment]
@Florence-Njeri I created the following PR. refer to https://github.com/asyncapi/generator/pull/944

**Comment by derberg** [comment]
related pr merged
